language: elixir

elixir:
  - 1.7.0
  - 1.7.1
  - 1.7.2
  - 1.7.3
  - 1.7.4

otp_release:
  - 21.0
  - 21.1
  - 21.2

env:
  global:
    - MIX_ENV=test

script:
  - mix do deps.get, deps.compile, coveralls.travis
  - mix credo --strict
