language: elixir

elixir:
  - 1.7.4
  - 1.8.1

otp_release:
  - 20.3
  - 21.3

env:
  global:
    - MIX_ENV=test

before_script:
  - MIX_ENV=test mix compile --warnings-as-errors

script:
  - mix credo --strict
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
  - mix coveralls.travis

sudo: required

dist: trusty

cache:
  directories:
    - _build
    - deps
