language: elixir

elixir:
  - 1.6.0
  - 1.6.1
  - 1.6.2
  - 1.6.3

otp_release:
  - 19.3
  - 20.0
  - 20.1
  - 20.2

env:
  global:
    - MIX_ENV=test

script:
  - mix do deps.get, deps.compile, coveralls.travis
  - mix credo --strict
