language: elixir

elixir:
  - 1.5.0
  - 1.5.1
  - 1.5.2
  - 1.6.0
  - 1.6.1

otp_release:
  - 19.3
  - 20.0

env:
  global:
    - MIX_ENV=test

script:
  - mix do deps.get, deps.compile, coveralls.travis
