language: elixir

elixir:
  # - 1.6.0
  # - 1.6.1
  # - 1.6.2
  # - 1.6.3
  # - 1.6.4
  # - 1.6.5
  - 1.6.6
  # - 1.7.0
  - 1.7.1

otp_release:
  # - 20.0
  # - 20.1
  # - 20.2
  - 20.3
  - 21.0

env:
  global:
    - MIX_ENV=test

script:
  - mix do deps.get, deps.compile, coveralls.travis
  - mix credo --strict
